// File generated by FlutterFire CLI, simplified for Android and iOS.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAM3Uv-lY2B1FoHzMwr3T4P62x_Wzu-MM',
    appId: '1:819312440023:android:c445b676c121622b657692',
    messagingSenderId: '819312440023',
    projectId: 'service-provider-7bf81',
    storageBucket: 'service-provider-7bf81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJtDE1v-jVxoNhlo29lHyZViPZPksWS8Q',
    appId: '1:819312440023:ios:838139459b2095cc657692',
    messagingSenderId: '819312440023',
    projectId: 'service-provider-7bf81',
    storageBucket: 'service-provider-7bf81.firebasestorage.app',
    iosBundleId: 'com.example.serviceProvider',
  );
}